version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.11.8
  working_directory: /tmp/workspace/terraform

jobs:
  validate_tffiles:
    <<: *terraform
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "e7:b9:b0:11:c0:60:8d:0a:b8:20:83:0a:b7:c0:d0:48"
#      - run:
#          name: Add github.com to ~/.ssh/known_hosts
#          command: mkdir ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: terraform init
          command: terraform init -input=false
      - run:
          name: Validate Terraform configurations
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done
      - run:
          name: Install tflint
          command: curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.4.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin

      - run:
          name: terraform plan
          command: terraform plan -var "access_key=${ACCESS}" -var "secret_key=${SECRET}" -out=terraform.plan

      - run:
          name: terraform apply
          command: terraform apply terraform.plan



workflows:
  version: 2
  build:
    jobs:
      - validate_tffiles
#      - deploy_terraform:
#          requires:
#            - validate_tffiles
#      - approve
#      - release

#  deploy_terraform:
#    <<: *terraform
#    steps:
#      - run:
#          name: terraform apply
#          command: terraform apply terraform.plan
