version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.10.4
  working_directory: /tmp/workspace/terraform

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
#      - run:
#          name: Add github.com to ~/.ssh/known_hosts
#          command: mkdir ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: terraform init
          command: terraform init -input=false
