version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.10.4
  working_directory: /tmp/workspace/terraform

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
#      - run:
#          name: Add github.com to ~/.ssh/known_hosts
#          command: mkdir ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: terraform init
          command: terraform init -input=false
      - run:
          name: terraform plan
          command: terraform plan -out=terraform.plan -var "access_key=${ACCESS}" -var "secret_key=${SECRET}"

workflows:
  version: 2
  build:
    jobs:
      - validate
#      - plan_examples
#      - approve
#      - release
